//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudMVC.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmployeeId { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string EmployeeName { get; set; }
        [Required(ErrorMessage = "Employee is required")]
        [EmailAddress(ErrorMessage = "Invalid email format")]
        public string EmployeeEmail { get; set; }
        [Required(ErrorMessage = "Aadhar is required")]
        public string AadharCardNumber { get; set; }
        [Required(ErrorMessage = "Contact is required")]
        [MinLength(10, ErrorMessage = "Phone number must be 10 digits")]
        [MaxLength(10, ErrorMessage = "Phone number must be 10 digits")]
        public string ContactNumber { get; set; }
        [Required(ErrorMessage = "Department is required")]
        public string Department { get; set; }
        [Required(ErrorMessage = "Designation is required")]
        public string Designation { get; set; }
        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "PinCode is required")]
        public string PinCode { get; set; }
        [Required(ErrorMessage = "Date of birth is required")]
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
